### ISSUE TITLE
don't record / display exception reason if it's empty

### ISSUE THREAD

**Issue by belm0** [itamarst/eliot#479]
I'm not sure if it should be handled when the exception action is created, or by eliot-tree, but this seems wasteful for case of None or empty exception reason:

```
eliot-tree foo.json
38dbd553-f8a3-44b2-a950-b78cfd6a8d75
└── ...
    └── twist/5 ⇒ failed 2021-11-24 15:01:38Z
        ├── exception: Bar
        └── reason: 
```

**Comment by itamarst** [comment]
In general this is probably a waste of space... but not always. Consider an API that does `raise KeyError(key)`. If the key is a blank string, that's still something you want to know when reading the logs, so you don't want the reason omitted in that case because it'd be confusing to the reader.

That being said, I wonder if `eliot-tree` should maybe use `repr()` on values? So you can tell difference between e.g. `12` or "`12`", or see if reason is a blank string. So you could file an issue there if you wish.

**Comment by belm0** [comment]
I'm not sure I follow your example about KeyError.  I don't think it's reasonable to be created with an empty string (as opposed to a string of one space, for the `space` key).

For one-off exception class definitions internal to a codebase, it's common for `str()` to yield an empty string (specifically `''`).

```python
class Foo(Exception): pass

>>> str(Foo())
''
```

If the author of the exception is not providing a str representation, it doesn't seem useful for eliot-tree to print a line.  Absence of the line implies an empty str() result.
