### ISSUE TITLE
Is there a no-op version of eliot

### ISSUE THREAD

**Issue by rouilj** [itamarst/eliot#488]
Hello:

I maintain the [Roundup Issue Tracker](https://www.roundup-tracker.org). Eliot looks like a useful tool for adding context to logging in development or production. But I don't want to require all my users to install Eliot just to run Roundup.

Is there a replacement that I can use if
```
  import eliot 
```
fails that will provide no-ops (mocks) for the eliot methods.

Roundup runs under both python 2.7 as well as 3.6+. In order to use newer eliot features under python3,
I would need this mock library for Python 2.7.
 
Thanks.

-- rouilj

**Comment by itamarst** [comment]
Hi, I don't really have the time to maintain that.

However: for a while Tahoe-LAFS, which uses Eliot, was supporting both Python 2 and Python 3 (in fact the code mostly still does) and we successfully had both working, with a few strategic if statements. I think most of the issues were that Eliot doesn't automatically do Unicode conversion for bytes on Python 3... but Python 3 version of Eliot also has the custom JSON encoder support, so that's how we solved it.

See https://github.com/tahoe-lafs/tahoe-lafs/blob/tahoe-lafs-1.17.1/src/allmydata/util/_eliot_updates.py, the `eliot_json_encoder`.

**Comment by rouilj** [comment]
Thanks for the reply.

I'll check out the lafs changes.
